### PR TITLE
Fix transcripts season 1 episode 0 & 4

### LINKED ISSUE #12: Fix transcript season 1 episode 0 and 4
## Issue Context

We need to fix the transcripts to be consistent by following the guidelines.

### PR DESCRIPTION
**Pull request by adiati98**
## Linked Issue

Closes #12 

## Description

- Fix transcript podcast season 1 episode 0 & 4

## Methodology
- Fix/edit transcript manually by listening to the episodes of the podcast.
- Following the transcriptions' guidelines.

### CODE REVIEW

**Comment by adiati98** [comment]
Hi @danieltott 

I fixed the transcription for episodes 0 & 4 to follow the guidelines.

I believe the timestamps are used for the podcast's video only?
Because I don't see any timestamps in the transcript on the website.

There are some overlap conversations (crosstalk) that didn't get pick up in the generated transcriptions.
So I added them, the timestamps, and edit the numbers of the paragraphs manually.
However, I don't know the exact timestamp.
So for instance, I did `00:46:31` instead of `00:46:31,619`.

We need to see if this still works well on the website.
If so, I will use this format going forward.

Thank you in advance, Dan! 😄

**Comment by danieltott** [comment]
@adiati98 we definitely use the timestamps on the site, and they're tied to the time on the podcast recording so we want to keep them.

I'd say just add `000` for the milliseconds value, that should be fine. So `00:46:31,000` should work.

Sorry for the delay getting back to this!

**Comment by adiati98** [comment]
> @adiati98 we definitely use the timestamps on the site, and they're tied to the time on the podcast recording so we want to keep them.
> 
> I'd say just add `000` for the milliseconds value, that should be fine. So `00:46:31,000` should work.
> 
> Sorry for the delay getting back to this!

Gotcha, @danieltott!
Let me fix them then 😄

**Comment by adiati98** [comment]
Hey @danieltott,
I've fixed the timestamps and pushed it 😊

**Comment by adiati98** [comment]
Hi @danieltott,
I would like to ask about the guide and the format of the transcripts. 
Is the format looks good (easy to read & understand)?

If so, I'm thinking to work on this backwards from the newest episode because I believe people will listen to the newer ones. 

Thank you 😊

**Comment by danieltott** [comment]
you're the best

**Pull request merged**
