### PR TITLE
Improve podcast season 1 episode 0 & 4 

### LINKED ISSUE #2: Improve Season 1 Episode 0
## Issue Context

Our podcast's transcriptions are automatically generated, so there would be typos or missing words. 

We want to improve every episode's transcription so they can be accessible for everyone. Currently, we are doing this manually.

## Steps To Update

- Open the file of the podcast's episode. 
  e.g.: `1_0.srt` means season 1 episode 0
-  Listen to the podcast's episode and improve the transcript based on what you hear.

## Accessibility Resources

- [Transcribing Audio to Text - W3C WAI](https://www.w3.org/WAI/media/av/transcribing/)

If you have questions or need help, please let us know.

### LINKED ISSUE #3: Improve Season 1 Episode 4
## Issue Context

Our podcast's transcriptions are automatically generated, so there would be typos or missing words. 

We want to improve every episode's transcription so they can be accessible for everyone. Currently, we are doing this manually.

## Steps To Update

- Open the file of the podcast's episode. 
  e.g.: `1_0.srt` means season 1 episode 0
-  Listen to the podcast's episode and improve the transcript based on what you hear.

## Accessibility Resources

- [Transcribing Audio to Text - W3C WAI](https://www.w3.org/WAI/media/av/transcribing/)

If you have questions or need help, please let us know.

### PR DESCRIPTION
**Pull request by adiati98**
## Linked Issue

- Closes #2
- Closes #3 

## Description

- Improve podcast season 1 
  - Episode 0
  - Episode 4

## Methodology
- Improve/edit transcript manually by listening to the episodes of the podcast.
- Keeping 2 lines for each timestamp as originally generated transcriptions.

### CODE REVIEW

**Comment by adiati98** [comment]
Hi @danieltott,
I improved the transcription starting from episode 4 (there is no transcription for episodes 1 - 3).

I tried to keep the format of the generated transcriptions, where there are only 2 lines for each timestamp.
However, for some timestamps, they are longer.
See for example below: 

**Original format:**
```
8
00:00:41,960 --> 00:00:45,079
Dan Ott: Thanks, Bekah. In this
episode, you'll hear from Vic
```

**Keeping the format, but becomes long**
```
792
00:48:32,099 --> 00:48:39,659
The low-code services. Airtable and Zapier, 
and just like the way different ways to hack like hook
```

Let me know if this format gives trouble such as indenting or anything when you update the transcription on the hosting platform.

I'm not sure if we should keep the conversation lines to be 2 lines but with the possibility of having long lines such as above,
or keeping them around the same length, but with more lines for longer conversation within the timeline.  

Either way, please let me know what's best.
I will continue improving them once we set the format.

Thank you! 😄

**Comment by adiati98** [comment]
Also, according to the W3C:

> Put non-speech sounds in parentheses, lowercase, italics, with a space before and after. For example:
( computer crashing into bits and parts sliding across the floor )

I googled how to make, (*laugh*) for example, to be italic.
But giving the tag `<i></i>` would make the whole line italic.
This is solely based on what I saw on Google, but I haven't tried it.
I haven't found a tool to check the preview of `.srt` files.

So all non-text audios so far are not italic.

Or should we take out the non-text audios?

**Review by danieltott — APPROVED** [review]
This is awesome, @adiati98 !!

**Comment by danieltott** [comment]
OK - so don't worry about the italic formatting. SRT files don't support those (or at least buzzsprout doesn't). But adding them is perfect.

I tested out the longer lines on buzzsprout and it seems to work ok for now... ¯\_(ツ)_/¯ I don't have the time to completely figure out everything about those, so since they seem to work on buzzsprout we're just going to go with it!

Thank you again ❤️ ❤️ ❤️

**Comment by adiati98** [comment]
Great to hear, @danieltott!
I can continue to work on them then 😃

**Pull request merged**
